version: "3.3"

services:
  my-server:
    build:
      context: ./rust_rocket_server
    restart: always
    environment:
      VIRTUAL_HOST: mader.xyz, www.mader.xyz
      LETENCRYPT_HOST: mader.xyz, www.mader.xyz
      LETENCRYPT_EMAIL: vincent.mader@icloud.com
    ports:
      - 5007:8000
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_my_awesome_proxy_network # same name as in `./proxy/docker-compose.yml` + prefix (see "docker network ls")
